### ISSUE TITLE
Two names for the same type convert to one type

### ISSUE THREAD

**Issue by cvvergara** [anthonytasca/pgrouting#5]
Two names for the same type convert to one type

```
typedef graph::Pgr_lineGraph <
boost::adjacency_list < boost::vecS, boost::vecS,
    boost::bidirectionalS,
    Line_vertex, Basic_edge >,
Line_vertex, Basic_edge > LinearDirectedGraph;


typedef graph::Pgr_turnPenaltyGraph <
boost::adjacency_list < boost::vecS, boost::vecS,
    boost::bidirectionalS,
    Line_vertex, Basic_edge >,
    Line_vertex, Basic_edge > LinearDirectedGraph;

```

- [x] create a file with a appropriate name put both types on the file (together with the namespace where they are defined)
- [ ] include the file in both .hpp files the line graph one and the turn penalty graph one
- [ ] coment out (#if 0 #endif) the definiations that are on both .hpp files
- [ ] compile until fixing bugs created by previous steps
- [ ] delete one of the types
- [ ] compile and fix where the compiler complains using the other type until no more errors

**Comment by anthonytasca** [comment]
I created a file that contains both typedefs b647c6cd8551aa62fd79e89a4a05282024dad27f

When i try to include this file in both of the .hpp files, comment out the other definitions, and compile, it tells me that there are duplicate definitions of LinearDirectedGraph. When I delete one of these declarations (graph::Pgr_lineGraph <..> LinearDirectedGraph for example) I get the following error:
```
src/lineGraph/lineGraph_driver.cpp error: variable 'pgrouting::LinearDirectedGraph line' has initializer but incomplete type
```

I am unsure about how to fix this.

**Comment by cvvergara** [comment]
Interesting when you put the stuff together you see that at the end they have the same name

https://github.com/anthonytasca/pgrouting/blob/b647c6cd8551aa62fd79e89a4a05282024dad27f/include/cpp_common/linear_directed_graph.h#L50

and

https://github.com/anthonytasca/pgrouting/blob/b647c6cd8551aa62fd79e89a4a05282024dad27f/include/cpp_common/linear_directed_graph.h#L56

have the same name.

So delete one of them, and consider your self on the step of:
compile until fixing bugs created by previous steps

lets see what happens

**Comment by anthonytasca** [comment]
In the previous comment i mentioned that when I delete one of these declarations (graph::Pgr_lineGraph <..> LinearDirectedGraph for example) I get the following error:
```
src/lineGraph/lineGraph_driver.cpp error: variable 'pgrouting::LinearDirectedGraph line' has initializer but incomplete type
```

**Comment by cvvergara** [comment]
ok, then I will do that when I go back to Mexico (I go back on the 2nd of November so on the 3rd I cans start looking at this)

**Comment by anthonytasca** [comment]
Great, thank you!

**Comment by anthonytasca** [comment]
This issue has been fixed in this commit: https://github.com/anthonytasca/pgrouting/commit/74b1dde268e3acc25c2f5af5654d06e4dddca770
